### PR TITLE
Prevent git from converting linebreaks on windows

### PR DESCRIPTION
**Pull request by not-an-aardvark**
Someone on windows should probably verify that this works. (After cloning the repo and running `npm test`, the linter should not report any linebreak style errors.)

### CODE REVIEW

**Comment by Raia** [comment]
>Expected linebreaks to be 'LF' but found 'CRLF'

**Comment by AlMcKinlay** [comment]
@Raia Did you do a clean clone or was this from an existing repository checked out?

Also, @not-an-aardvark we should probably do autocrlf=false as well.

**Comment by Raia** [comment]
@YaManicKill, it's a clean clone.

**Comment by AlMcKinlay** [comment]
Ah wait, I think it's because you have to clone master first, and then the branch. Git attributes are a little complicated in that matter. I'll merge this and test it, and see what it does.

**Review by AlMcKinlay — APPROVED** [review]

**Comment by AlMcKinlay** [comment]
Aaactually, I'm not going to merge, because I just tested the branch myself and it worked fine for me.

@Raia Are you sure it didn't work for you?

**Comment by Raia** [comment]
@YaManicKill, I can try again in the evening. If it worked for you I probably did something wrong.

**Comment by AlMcKinlay** [comment]
This is what I did:

1. Check out master
2. Run npm test, see the line ending errors
3. Check out gitattributes branch
4. Run npm test, no line ending errors

**Comment by Raia** [comment]
Yeah, I screwed up :p Go for it.

**Pull request merged**
